[target.x86_64-pc-windows-gnu]
image = "rustembedded/cross:x86_64-pc-windows-gnu"

[target.x86_64-unknown-linux-gnu]
image = "rustembedded/cross:x86_64-unknown-linux-gnu"

[target.i686-pc-windows-gnu]
image = "rustembedded/cross:i686-pc-windows-gnu"

[target.i686-unknown-linux-gnu]
image = "rustembedded/cross:i686-unknown-linux-gnu"

[target.aarch64-pc-windows-gnullvm]
image = "rustembedded/cross:aarch64-pc-windows-gnullvm"

[target.aarch64-unknown-linux-gnu]
image = "rustembedded/cross:aarch64-unknown-linux-gnu"